---
- name: Load variables
#include_vars - Load variables from files, dynamically within a task
#https://docs.ansible.com/ansible/2.7/modules/include_vars_module.html
  include_vars: "{{ item }}"
  #https://ansible-tips-and-tricks.readthedocs.io/en/latest/os-dependent-tasks/variables/
  with_first_found:
    - files:
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution|lower }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution|lower }}.yml"
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family|lower }}.yml"
        - defaults.yml
      paths:
        - ../common/vars
  tags:
    - load_vars

- name: Install required packages
# This module actually calls the pertinent package modules for each
#system (apt, yum, etc).
  package:
    name: "{{ item }}"
    # equivalent to yum check-update
    #The command will refresh the package index and check for available updates
    update_cache: yes
    # install package = make use is present
    state: installed
  # http://jinja.pocoo.org/docs/dev/templates/#join
  # join filter concatenate package items with ,
  with_items: "{{ packages | join(',') }}"

- name: Install Java
  include_tasks: java.yml
  when: java != "embedded"
  tags:
    - java

- name: Fail test
  fail:
    msg: "fail test"
  when: java == "openjdk" and ansible_os_family|lower == "suse" and ansible_distribution_major_version|int == "11"

- name: Make sure the NTP service is started
  service:
    name: "{{ ntp_service_name }}"
    state: started

- name: Make sure the NTP service is enabled
  service:
    name: "{{ ntp_service_name }}"
    enabled: yes
  ignore_errors: true

# controle des ressources sys
# https://www.admin-linux.fr/controle-des-ressources-systemes-ulimit/
- name: Set nofile and nproc limits
  blockinfile:
    path: /etc/security/limits.d/99-hadoop.conf
    create: yes
    mode: 0644
    block: |
      * soft nofile 32768
      * hard nofile 32768
      * soft nproc 32768
      * hard nproc 32768
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
#https://community.hortonworks.com/articles/33522/swappiness-setting-recommendation.html
- name: Set swappiness to {{ swappiness }}
  sysctl:
    name: vm.swappiness
    value: "{{ swappiness }}"
    state: present
    reload: yes
    # ignoreerrors: yes
  tags:
    - swappiness

- block:
    - name: Stop the firewall service
      service:
        name: "{{ firewall_service_name }}"
        state: stopped
      ignore_errors: true

    - name: Disable the firewall service
      service:
        name: "{{ firewall_service_name }}"
        enabled: no
      ignore_errors: true
  when: disable_firewall and firewall_service_name is defined
  tags:
    firewall

- name: Disable selinux
  selinux:
    state: disabled
  when: ansible_os_family|lower == "redhat" and ansible_distribution|lower != "amazon"

- name: Disable Transparent Huge Pages until the next reboot
  shell: echo never > /sys/kernel/mm/transparent_hugepage/enabled && echo never > /sys/kernel/mm/transparent_hugepage/defrag
  args:
    removes: /sys/kernel/mm/transparent_hugepage/enabled

- name: Disable Transparent Huge Pages in Grub 2
  lineinfile:
    path: /etc/default/grub
    state: present
    line: 'GRUB_CMDLINE_LINUX=$GRUB_CMDLINE_LINUX" transparent_hugepage=never"'
  when: (ansible_os_family|lower == "redhat" and ansible_distribution_major_version|int >= 7) or
        (ansible_distribution|lower == "amazon" and ansible_distribution_version|int >= 2) or
        (ansible_os_family|lower == "debian" and ansible_distribution_major_version|int >= 7) or
        (ansible_os_family|lower == "suse" and ansible_distribution_major_version|int >= 12)
  notify: Generate the Grub config file
# execute handlers (if any called) immediately do not wait until the end of the play
- meta: flush_handlers

# check utility before adding
# - name: Configure tuned (RHEL/CentOS 7)
#   include_tasks: tuned.yml
#   when: ansible_os_family|lower == "redhat" and ansible_distribution_major_version|int == 7
